version: '3.8'

services:
  table-extractor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: table-extractor
    ports:
      - "8501:8501"
    volumes:
      - ./scratch:/app/scratch
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 1G
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    restart: unless-stopped
    networks:
      - table-extract-net

networks:
  table-extract-net:
    driver: bridge